### ISSUE TITLE
Add gdx-skins to assets section

### ISSUE THREAD

**Issue by czyzby** [jelhouss/libgdx_suit#3]
The [gdx-skins](https://github.com/czyzby/gdx-skins) repository contains open sourced Scene2D skin assets, as well as a lot of links to tutorials and third-party tools. I'm obviously biased, being the author, but I think it could be useful to people trying to figure out the LibGDX GUI API. You can also go through the resources listed in the `README` and include some of them in this repository.

**Comment by jelhouss** [comment]
Great @czyzby , gdx-skins is now added! :)
Seems fantastic! I mean I was out of the framework zone for like 2 years now, never had the time to come back and code a little, that's the reason I haven't heard of this! Now added to Assets section. I forgot also to add Scene2D to Tools section being a piece of the ecosystem for LibGDX, your project reminded me to do so!

Thank you for suggesting this! :)
Feel free to share any other suggestions! :)

**Comment by czyzby** [comment]
You can remove the _czyzby_ credit from the `README` file - it just seems a bit unfair, as I only collected the skins that other people published for free. ; )

Also, I'd remove the `What the f**k is this?` at the beginning. It just seems unnecessary.

Anyway, I suggest looking through existing third-party LibGDX libraries and listing them categorized by purpose. Unofficial [gdx-setup](https://github.com/czyzby/gdx-setup) allows to include most of libraries in the generated projects, you can look into that first.

Maybe you could turn this repository into an [Awesome LibGDX](https://github.com/sindresorhus/awesome) list? It should get more exposure.

**Comment by jelhouss** [comment]
You need a credit mate as long as you credit others! I mean credit goes for the package of "stuff" you collected and maintaining, however I will delete it if this is your wish.

The "WTF" title was something that came from a moment of sarcasm haha... I will edit it too! 

In the first place I wanted to make it awesome alternative for libgdx... but I just wrote the first resources "just as it is" with simple markdown tags, then I found myself adding resources and keeping the markdown as it is. However it is not going to be a problem changing the markdown and make it awesome-alternative. I am going to do that later, I opened an issue for better markdown styling proposals, I guess I will edit the requirements so we can get "Awesome alternative README" I just hope I don't have this open for long, I'll try to keep this updated!
